//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.PicInActivity = new HashSet<PicInActivity>();
        }
    
        public int Ac_ID { get; set; }
        public string Ac_Pic { get; set; }
        public string Ac_Name { get; set; }
        public string Ac_Mes { get; set; }
        public System.DateTime Ac_Sta_Time { get; set; }
        public System.DateTime Ac_Sto_Time { get; set; }
        public int IsAct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicInActivity> PicInActivity { get; set; }
    }
}
