//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Album_Comment = new HashSet<Album_Comment>();
            this.Album_Point = new HashSet<Album_Point>();
            this.Album_Save = new HashSet<Album_Save>();
            this.Picture_In_Album = new HashSet<Picture_In_Album>();
        }
    
        public int Alb_ID { get; set; }
        public int UID { get; set; }
        public string Alb_Name { get; set; }
        public string Alb_Pic { get; set; }
        public string Alb_Mes { get; set; }
        public System.DateTime Alb_Time { get; set; }
    
        public virtual Album Album1 { get; set; }
        public virtual Album Album2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album_Comment> Album_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album_Point> Album_Point { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album_Save> Album_Save { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture_In_Album> Picture_In_Album { get; set; }
    }
}
