//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pic_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pic_Comment()
        {
            this.Pic_Comment_Comment = new HashSet<Pic_Comment_Comment>();
        }
    
        public int PC_ID { get; set; }
        public int UID { get; set; }
        public int Pic_ID { get; set; }
        public string PC_Mes { get; set; }
        public Nullable<System.DateTime> PC_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pic_Comment_Comment> Pic_Comment_Comment { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
